prueba/repositorio/blog/apps/noticias/urls.py
from django.urls import path
from . import views

app_name = 'noticias'

urlpatterns = [
    
    path('', views.inicio, name= "inicio"),
    
    ]

prueba/repositorio/blog/apps/usuarios/urls.py
#from django.urls import path
#from . import views

#app_name = 'usuarios'

#urlpatterns = [
    
 #   path('', views.inicio, name= "inicio"),
    
  #  ]

prueba/repositorio/blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include #importamos include para poder trabajar con la url de noticias
#from apps.noticias import views
from . import views
#URL de login
from django.contrib.auth import views as auth

#URL PRINCIPAL
urlpatterns = [
    #path('', views.inicio, name="inicio"),
    path('admin/', admin.site.urls),
    # paht para la url de la vista de home
    path('', views.home, name="home"),
    #paht tiene 3 parametros de direccion url, funcion de la vista(views)
    #paht de nosotros
    path('nosotros/', views.nosotros, name="nosotros"),
    
    # ----------- URL APP NOTICIAS -----------
    path('noticia/', include('apps.noticias.urls') ),
    
    #LOGIN
    #path('usuarios/login', views.login, name="login")
    path("login/", auth.LoginView.as_view(template_name='usuarios/login.html'), name= 'login'),
    path("logout/", auth.LoginView.as_view(), name='logout'),    
    ] 

prueba/repositorio/blog/apps/noticias/models.py
from django.db import models

# Create your models here.

prueba/repositorio/blog/apps/usuarios/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser

class Usuarios(AbstractUser):
    pass

prueba/repositorio/blog/apps/noticias/views.py
from django.shortcuts import render, HttpResponse

# Create your views here.

#def inicio(request):
#   return HttpResponse("<h1>HOLA MUNDO</h1> <h2> desde django</h2>")

def inicio(request):
    return render(request, 'noticias/inicio.html')

prueba/repositorio/blog/apps/usuarios/views.py
from django.shortcuts import render

# Create your views here.

prueba/repositorio/blog/blog/views.py
from django.shortcuts import render

def home(request):
    return render(request, "home.html")

def nosotros(request):
    return render(request, "nosotros.html")

#def login(request):
#    if request.method == 'POST':
 #       email = request.POST.get('email')
  #      password = request.POST.get('password')    
   #     print(email)
    #    print(password)
    #return render(request, "usuarios/login.html")

prueba/repositorio/blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/main.css'%}">
    <title>blog| {% block titulo %} {% endblock titulo %}  </title>
</head>
<body class="contenedor">

    <div>
        <a href="{% url 'nosotros'%}">nosotros template</a>       
        <a href="{% url 'home'%}">template home</a>
        <a href="{% url 'noticias:inicio'%}">template noticia</a>

        {% if user.is_uthenticated %}
        <p> Bienvenido {{user.username}} </p>
        <a href="{% url 'logout' %}">cerrar sesion</a>
        {% else %} 
        <a href="{% url 'login' %}">iniciar sesion</a>
        
        {% endif %}
    <div>
    {% block contenido %}
    {% endblock contenido %}

    
</body>
</html6>

prueba/repositorio/blog/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %} home {% endblock titulo %}

{% block contenido %}
    <h1>Este es el inicio de nuestro blog🤣 Probando</h1>
    <img src="https://www.maestrosdelweb.com/images/2012/04/esquema-mtv.png" alt="error" height='150px'>
{% endblock contenido %}   

prueba/repositorio/blog/templates/nosotros.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %} nosotros {% endblock titulo %}

{% block contenido %}
    <h1>Nosotros: Quienes somos</h1>
{% endblock contenido %} 

prueba/repositorio/blog/templates/noticias/inicio.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %} noticias {% endblock titulo %}

{% block contenido %}
<h2>Soy las noticias</h2>
<img src="https://www.noticiasdelacalle.com.ar/Media/Tapas/D-2023-07-14.jpg">
{% endblock contenido %}

prueba/repositorio/blog/templates/usuarios/login.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}
<form method="POST"> {% csrf_token %}
    <input type="text" placeholder="usuario">   
    <input type="password" placeholder="contraseña">
    <input type="submit">  
<form>  
{% endblock contenido %}  